copy ci from darwin-nix

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,13 +15,23 @@ jobs:
         uses: cachix/install-nix-action@v27
         with:
           nix_path: nixpkgs=channel:nixos-unstable
-      - name: Install dependencies
+      - name: Install nixpkgs-unstable channel
         run: |
-          nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer
-          ./result/bin/darwin-installer
-          nix-channel --add http://nixos.org/channels/nixpkgs-unstable nixpkgs
+          nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
           nix-channel --update
           nix-env -iA nixfmt-rfc-style -f '<nixpkgs>'
+      - name: Install nix-darwin and test
+        run: |
+          export NIX_PATH=$HOME/.nix-defexpr/channels
+          # We run nix-darwin twice to test that it can create darwin-configuration correctly for us
+          # but we expect it to fail setting up /etc/nix/nix.conf
+          nix-shell -A installer || true
+          nixConfHash=$(shasum -a 256 /etc/nix/nix.conf | cut -d ' ' -f 1)
+          /usr/bin/sed -i.bak \
+            "s/# nix.package = pkgs.nix;/nix.settings.access-tokens = [ \"github.com=\${{ secrets.GITHUB_TOKEN }}\" ]; environment.etc.\"nix\/nix.conf\".knownSha256Hashes = [ \"$nixConfHash\" ];/" \
+            ~/.nixpkgs/darwin-configuration.nix
+          nix-shell -A installer
+          nix-shell -A installer.check
       - uses: cachix/cachix-action@v14
         with:
           name: mycache
@@ -34,4 +44,6 @@ jobs:
           echo this workflow was triggered by ${{github.actor}}
           find . -name '*.nix' | xargs nixfmt -c
       - name: Darwin build
-        run: darwin-rebuild build -I ./MacOs/system/darwin-configuration.nix
+        run: |
+          . /etc/static/bashrc
+          darwin-rebuild build -I ./MacOs/system/darwin-configuration.nix
